site_name: CEM
site_description: WePositive-DI
repo_url: https://github.com/WePositive-energy/wepositive-di
docs_dir: docs
site_dir: docs_html
use_directory_urls: false

theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: light green
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_symbol_type_heading: true
            members: true
            members_order: source
            inherited_members: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - toc:
      permalink: true

nav:
  - Home: README.md
